/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pbo08;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author evfi2
 */
public class PBO0801_JFRAME extends javax.swing.JFrame {
    
    public int itung=1;
    public String[] savedata;
    public int panjangkolom;
    public int panjangrow;
    int itungklik=0;
    int itungawal;
    int itungakhir;
        

    /**
     * Creates new form PBO08_JFRAME
     */
    
    public PBO0801_JFRAME() 
    {
        initComponents();
        
        setLocationRelativeTo(null);
        cb1.addItem("Pilih Genre");
        cb1.addItem("Romantis");
        cb1.addItem("Misteri");
        fillTable("try","Try","Genre");
        fillTable("singa","rima","Kuda");
        fillTable("Merah","Kuning","Hijau"
                + "");
//        System.out.println("jumlah : "+Tabel_dataBuku.getColumnCount());
//        System.out.println("jumlah : "+Tabel_dataBuku.getRowCount());
//        System.out.println("kolom 1 row 0: "+Tabel_dataBuku.getValueAt(0, 0));
//        System.out.println("kolom 2 row 0: "+Tabel_dataBuku.getValueAt(0, 1));
//        System.out.println("kolom 3 row 0: "+Tabel_dataBuku.getValueAt(0, 2));
//        System.out.println("kolom 1 row 0: "+Tabel_dataBuku.getValueAt(1, 0));
//        System.out.println("kolom 2 row 0: "+Tabel_dataBuku.getValueAt(1, 1));
//        System.out.println("kolom 3 row 0: "+Tabel_dataBuku.getValueAt(1, 2));
        //scanningsearch();
        
        
        
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Panel_formBuku = new javax.swing.JPanel();
        Label_judul = new javax.swing.JLabel();
        Label_Penulis = new javax.swing.JLabel();
        Label_Genre = new javax.swing.JLabel();
        Judul_Input = new javax.swing.JTextField();
        Penulis_Input = new javax.swing.JTextField();
        Tombol_Masukkan = new javax.swing.JButton();
        Tombol_Kosongkan = new javax.swing.JButton();
        cb1 = new javax.swing.JComboBox<>();
        Panel_dataBuku = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel_dataBuku = new javax.swing.JTable();
        JUDULPOPUP = new javax.swing.JLabel();
        Input_Search = new javax.swing.JTextField();
        Search_Button = new javax.swing.JButton();
        Delete_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_formBuku.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Form Buku", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        Label_judul.setText("Judul");

        Label_Penulis.setText("Penulis");

        Label_Genre.setText("Genre");

        Judul_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Judul_InputActionPerformed(evt);
            }
        });

        Penulis_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Penulis_InputActionPerformed(evt);
            }
        });

        Tombol_Masukkan.setText("Masukkan");
        Tombol_Masukkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tombol_MasukkanActionPerformed(evt);
            }
        });

        Tombol_Kosongkan.setText("Kosongkan");
        Tombol_Kosongkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tombol_KosongkanActionPerformed(evt);
            }
        });

        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_formBukuLayout = new javax.swing.GroupLayout(Panel_formBuku);
        Panel_formBuku.setLayout(Panel_formBukuLayout);
        Panel_formBukuLayout.setHorizontalGroup(
            Panel_formBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_formBukuLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(Panel_formBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_formBukuLayout.createSequentialGroup()
                        .addComponent(Label_Penulis, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Penulis_Input))
                    .addGroup(Panel_formBukuLayout.createSequentialGroup()
                        .addComponent(Label_Genre, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(Panel_formBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_formBukuLayout.createSequentialGroup()
                                .addComponent(Tombol_Masukkan, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Tombol_Kosongkan))
                            .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Panel_formBukuLayout.createSequentialGroup()
                        .addComponent(Label_judul, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Judul_Input)))
                .addGap(15, 15, 15))
        );
        Panel_formBukuLayout.setVerticalGroup(
            Panel_formBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_formBukuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_formBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_judul)
                    .addComponent(Judul_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_formBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Penulis)
                    .addComponent(Penulis_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_formBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Genre)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(Panel_formBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tombol_Masukkan)
                    .addComponent(Tombol_Kosongkan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel_dataBuku.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Buku", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        Tabel_dataBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Pengarang", "Genre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabel_dataBuku);

        javax.swing.GroupLayout Panel_dataBukuLayout = new javax.swing.GroupLayout(Panel_dataBuku);
        Panel_dataBuku.setLayout(Panel_dataBukuLayout);
        Panel_dataBukuLayout.setHorizontalGroup(
            Panel_dataBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_dataBukuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        Panel_dataBukuLayout.setVerticalGroup(
            Panel_dataBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_dataBukuLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addContainerGap())
        );

        JUDULPOPUP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JUDULPOPUP.setText("Buku App");

        Input_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_SearchActionPerformed(evt);
            }
        });

        Search_Button.setText("Cari");
        Search_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_ButtonActionPerformed(evt);
            }
        });

        Delete_Button.setText("Hapus");
        Delete_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_dataBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_formBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(Delete_Button)
                            .addComponent(JUDULPOPUP, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(180, 180, 180))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Input_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Search_Button)
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(JUDULPOPUP)
                .addGap(18, 18, 18)
                .addComponent(Panel_formBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Search_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Input_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_dataBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Delete_Button)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void Search_ButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        itungawal=itungklik;
        String text = Input_Search.getText();
        DefaultTableModel model = (DefaultTableModel)Tabel_dataBuku.getModel();
        TableRowSorter tr = new TableRowSorter(model);
        Tabel_dataBuku.setRowSorter(tr);
        // TODO add your handling code here:
        tr.setRowFilter(RowFilter.regexFilter(text));
        if(!text.equals("")){
            itungklik++;
        }
        itungakhir=itungklik;
    }                                             

    private void Judul_InputActionPerformed(java.awt.event.ActionEvent evt) {                                            
    Judul_Input.setText("");
    }                                           

    private void Penulis_InputActionPerformed(java.awt.event.ActionEvent evt) {                                              
    Penulis_Input.setText("");
    }                                             

    private void Tombol_KosongkanActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        Judul_Input.setText("");
        Penulis_Input.setText("");
        cb1.setSelectedIndex(0);
        
        // TODO add your handling code here:
    }                                                

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {                                    
 
    }                                   

    private void Tombol_MasukkanActionPerformed(java.awt.event.ActionEvent evt) {                                                
        String pesan;
        if((Penulis_Input.getText().equals("")||
                (Judul_Input.getText().equals(""))||
                (cb1.getSelectedItem().equals("Pilih Genre")))||
                ((Penulis_Input.getText().equals("")&&
                (Judul_Input.getText().equals(""))&&
                (cb1.getSelectedItem().equals("Pilih Genre"))))){
            pesan = "Data tidak boleh kosong";
            JOptionPane.showMessageDialog(null, pesan);
        }
        else{
            String judul = Judul_Input.getText();
            String Penulis = Penulis_Input.getText();
            String Genre = String.valueOf(cb1.getSelectedItem());
            if(scanningsearch(judul)&&scanningsearch(Penulis)&&scanningsearch(judul)){
                pesan = "Data sudah pernah diinput";
                JOptionPane.showMessageDialog(null, pesan);
            }
            else{
                fillTable(judul,Penulis,Genre);
            }  
        }
        // TODO add your handling code here:
    }                                               

    private void Delete_ButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        Tabel_dataBuku.getSelectedRow();
        System.out.println("work");
        DefaultTableModel model = (DefaultTableModel) Tabel_dataBuku.getModel();
        System.out.println("work");
        int selectedRow = Tabel_dataBuku.getSelectedRow();
        System.out.println("total Row : "+Tabel_dataBuku.getRowCount());
        System.out.println("Row : "+selectedRow);
        
        String text;
        
        if (selectedRow != -1) {
            if(itungawal==itungakhir){
                System.out.println(" if work");
                text = String.valueOf(Tabel_dataBuku.getValueAt(selectedRow,0));
                int respon = JOptionPane.showConfirmDialog(this, "Hapus "+text,"Perhatian", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if(respon == JOptionPane.YES_OPTION){
                    model.removeRow(selectedRow);
                    JOptionPane.showMessageDialog(null, text+" dihapus");
                }
                System.out.println(" if work");
                
            }
            else{
                
                int modelRow = Tabel_dataBuku.convertRowIndexToModel(selectedRow);
                text = String.valueOf(Tabel_dataBuku.getValueAt(selectedRow,0));
                
                int respon = JOptionPane.showConfirmDialog(this, "Hapus "+text,"Perhatian", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if(respon == JOptionPane.YES_OPTION){
                    model.removeRow(modelRow);
                    JOptionPane.showMessageDialog(null, text+" dihapus");
                }
                
                
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pilih baris yang ingin dihapus.");
        }
        // TODO add your handling code here:
        
        
    }                                             

    private void Input_SearchActionPerformed(java.awt.event.ActionEvent evt) {                                             
        Input_Search.setText("");
        // TODO add your handling code here:
    }                                            
    public Boolean scanningcb1(String item){
        int itemCount = cb1.getItemCount();
        Boolean back = false;
        for(int i=0;i<itemCount;i++){
            if((cb1.getItemAt(i).equals(item))){
                back = true;
            }
           
        }
        return back;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PBO0801_JFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PBO0801_JFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PBO0801_JFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PBO0801_JFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PBO0801_JFRAME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton Delete_Button;
    private javax.swing.JTextField Input_Search;
    private javax.swing.JLabel JUDULPOPUP;
    private javax.swing.JTextField Judul_Input;
    private javax.swing.JLabel Label_Genre;
    private javax.swing.JLabel Label_Penulis;
    private javax.swing.JLabel Label_judul;
    private javax.swing.JPanel Panel_dataBuku;
    private javax.swing.JPanel Panel_formBuku;
    private javax.swing.JTextField Penulis_Input;
    private javax.swing.JButton Search_Button;
    private javax.swing.JTable Tabel_dataBuku;
    private javax.swing.JButton Tombol_Kosongkan;
    private javax.swing.JButton Tombol_Masukkan;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   

    public void reset(){
        
        //comboBox.setSelectedIndex(0);
        
    }
    
    public void fillTable(String Judul,String Pengarang,String Genre){
        DefaultTableModel model = (DefaultTableModel)Tabel_dataBuku.getModel();
        model.addRow(new Object[]{Judul,Pengarang,Genre});
       
    }
    public void cleartable(){
        
        DefaultTableModel model = (DefaultTableModel)Tabel_dataBuku.getModel();
        model.setRowCount(0);
        model.setColumnCount(0);
    }
    public Boolean scanningsearch(String text){
        Boolean back=false;
        for(int kolom=0;kolom<Tabel_dataBuku.getColumnCount();kolom++){
            for(int row=0;row<Tabel_dataBuku.getRowCount();row++){
                if(String.valueOf(Tabel_dataBuku.getValueAt(row, kolom)).contains(text)){
                    back = true;
                }
            }
        }
        return back;
    }
    public void search(){
        
    }
}

